name: Build on Contentful Publish Event
on:
    repository_dispatch:
        types: [publish-channel-configuration]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "SpaceID: ${{ github.event.client_payload.spaceId }} - SpaceName: ${{ github.event.client_payload.spaceName }} - Environment: ${{ github.event.client_payload.environment }}"'

      - uses: actions/checkout@v3
        with:
         ref: main

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - run: npm install
      - run: node fetch-channel-configuration.js -s ${{ github.event.client_payload.spaceId }} -sn ${{ github.event.client_payload.spaceName }} -e ${{ github.event.client_payload.environment }} -a ${{ secrets.ACTIONS_CONTENTFUL_API_KEY }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: GH-Action Update product details
