name: Build on Contentful Publish Event
on:
    repository_dispatch:
        types: [publish-event]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Deploy
        uses: cmgriffing/scully-gh-pages-action@v9
        with:
          access-token: ${{ secrets.ACTION_DEPLOY_KEY }}
