name: Build on Contentful Publish Event
on:
    repository_dispatch:
        types: [publish-event]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Deploy
        uses: cmgriffing/scully-gh-pages-action@v9
        with:
          access-token: ${{ secrets.ACTION_DEPLOY_KEY }}
          deploy-branch: gh-pages
          build-args: --prod
