name: Build on Contentful Publish Event
on:
    repository_dispatch:
        types: [publish-event]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "SpaceID: ${{ github.event.client_payload.spaceId }}"'
      - uses: actions/checkout@v1
        with: 
         ref: ${{ github.head_ref }}

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - run: npm install
      - run: node fetch-product-details.js -s u962r8i34sue -e develop -a CFPAT-itlHJqIJT2WzBrQO4FdUwuOT6ShCg562nv_D0XX_HKI
      
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: GH-Action Update product details
