name: Build on push
on:
    push:
        branches:
         - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - run: npm ci
      - run: npm run build && npm run scully
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACTION_DEPLOY_KEY }}
          publish_dir: dist/rsx-ssr
