on: push
name: Publish App to Akamai
jobs:
  web-deploy:
    name: 🚀 Deploy Website to Akamai Every Commit
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get Latest Code
        uses: actions/checkout@v3

      - name: 📂 Sync Files
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: ravago-ssg-uat-nsu.sftp.upload.akamai.com
          remote-user: ns_ravago-ssg-uat
          private-ssh-key: ${{ secrets.AKAMAI_SSH_KEY }}
          source-path: ./dist/static/
          ssh-port: 22
          destination-path: ~/
          rsync-options: --dry-run



