on: push
  jobs:
    build-and-deploy:
      steps:
        - name: Install SSH Key
          uses: shimataro/ssh-key-action@v2
          with:
            key: ${{ secrets.AKAMAI_SSH_KEY }}
            known_hosts: unnecessary

        - name: Adding Known Hosts
          run: ssh-keyscan -p 22 -H ravago-ssg-uat.ssh.upload.akamai.com  >> ~/.ssh/known_hosts

        - name: Deploy with rsync
          run: rsync -avz -e "ssh -p 22" ./dist/static sshacs@$ravago-ssg-uat.ssh.upload.akamai.com:/



