on: push
name: Publish App to Akamai
jobs:
  web-deploy:
    name: 🚀 Deploy Website to Akamai Every Commit
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get Latest Code
        uses: actions/checkout@v3

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.AKAMAI_SSH_KEY }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-private-key: ${{ secrets.AKAMAI_SSH_KEY }}
          ssh-host: ravago-ssg-uat.ssh.upload.akamai.com

      - name: Deploy with rsync
        run: rsync -avz -e "ssh -p 22" ./dist/static sshacs@ravago-ssg-uat.ssh.upload.akamai.com:/
